export const PERMISSIONS = {
  SEND_MESSAGE: 'message:send',
  CREATE_GROUP: 'group:create',
  CREATE_CLUB: 'club:create',
  CREATE_BLACKBOARD_POST: 'blackboard:post:create',
  DELETE_OWN_MESSAGE: 'message:delete:own',
  DELETE_ANY_MESSAGE: 'message:delete:any',
  REPORT_MESSAGE: 'message:report',
  REVIEW_REPORT: 'report:review',
  INITIATE_CHAT_WITH_STUDENT: 'chat:initiate:student',
  INITIATE_CHAT_WITH_TEACHER: 'chat:initiate:teacher',
  INITIATE_CHAT_WITH_ADMIN: 'chat:initiate:admin',
  INITIATE_CHAT_WITH_HEADMASTER: 'chat:initiate:headmaster',
  INITIATE_CHAT_WITH_COMPLIANCE_OFFICER: 'chat:initiate:compliance_officer',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// We map each role to its default set of boolean permissions
export const DEFAULT_ROLE_PERMISSIONS: Record<
  string,
  Record<PermissionKey, boolean>
> = {
  student: {
    'message:send': true,
    'group:create': false,
    'club:create': false,
    'blackboard:post:create': false,
    'message:delete:own': true,
    'message:delete:any': false,
    'message:report': true,
    'report:review': false,
    'chat:initiate:student': false,
    'chat:initiate:teacher': true,
    'chat:initiate:admin': true,
    'chat:initiate:headmaster': true,
    'chat:initiate:compliance_officer': false,
  },
  teacher: {
    'message:send': true,
    'group:create': true,
    'club:create': true,
    'blackboard:post:create': true,
    'message:delete:own': true,
    'message:delete:any': false,
    'message:report': true,
    'report:review': false,
    'chat:initiate:student': true,
    'chat:initiate:teacher': true,
    'chat:initiate:admin': true,
    'chat:initiate:headmaster': true,
    'chat:initiate:compliance_officer': false,
  },
  admin: {
    'message:send': true,
    'group:create': true,
    'club:create': true,
    'blackboard:post:create': true,
    'message:delete:own': true,
    'message:delete:any': true,
    'message:report': true,
    'report:review': true,
    'chat:initiate:student': true,
    'chat:initiate:teacher': true,
    'chat:initiate:admin': true,
    'chat:initiate:headmaster': true,
    'chat:initiate:compliance_officer': false,
  },
  headmaster: {
    'message:send': true,
    'group:create': true,
    'club:create': true,
    'blackboard:post:create': true,
    'message:delete:own': true,
    'message:delete:any': true,
    'message:report': true,
    'report:review': true,
    'chat:initiate:student': true,
    'chat:initiate:teacher': true,
    'chat:initiate:admin': true,
    'chat:initiate:headmaster': true,
    'chat:initiate:compliance_officer': false,
  },
  compliance_officer: {
    'message:send': false,
    'group:create': false,
    'club:create': false,
    'blackboard:post:create': false,
    'message:delete:own': false,
    'message:delete:any': true,
    'message:report': false,
    'report:review': true,
    'chat:initiate:student': false,
    'chat:initiate:teacher': false,
    'chat:initiate:admin': false,
    'chat:initiate:headmaster': false,
    'chat:initiate:compliance_officer': false,
  },
};
